version: '2.1'

services:
  web:
    container_name: web
    ports:
      - '8000:8000'
    build: .
    volumes:
      - ./books:/books
    depends_on:
      postgresql-slave:
        condition: service_healthy
    command: bash init.sh
    restart: always
  postgresql-master:
    hostname: postgresql-master
    container_name: master
    image: 'bitnami/postgresql:12'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost"]
      retries: 10
    restart: always
  postgresql-slave:
    hostname: postgresql-slave
    container_name: slave
    image: 'bitnami/postgresql:12'
    ports:
      - '5433:5432'
    depends_on:
      postgresql-master:
        condition: service_healthy

    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost"]
      retries: 10
    restart: always

volumes:
  postgresql_master_data:
    driver: local
